### ISSUE TITLE
 files_textviewer: 1.0.3 does not work with 10.4.0

### ISSUE THREAD

**Issue by cdamken** [miqrogroove/files_textviewer#1]
Now it appears an icon  and shows all the files directory

**Comment by miqrogroove** [comment]
Thank you for the message.  I thought all 10.x versions were supposed to be compatible.  I will have to test the upgrade and see what changed now.

**Comment by cdamken** [comment]
I only can see in the log files:
```
{"reqId":"hfoKAA3UjIsMIH9c6WVl","level":0,"time":"2020-04-16T17:46:36+02:00","remoteAddr":"10.1.10.100","user":"carlos","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/files_textviewer\/","message":"token ffee8cc4ff3314018b5615669a558f46a66a6465a71e094fee40ae73952cd88b3b3cb39b8d91dbee10fd4cda00b876045c7f9d7d39b80c32147225d6d3a4d06f with token id 274039 found, validating"}
{"reqId":"hfoKAA3UjIsMIH9c6WVl","level":0,"time":"2020-04-16T17:46:36+02:00","remoteAddr":"10.1.10.100","user":"carlos","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/files_textviewer\/","message":"token ffee8cc4ff3314018b5615669a558f46a66a6465a71e094fee40ae73952cd88b3b3cb39b8d91dbee10fd4cda00b876045c7f9d7d39b80c32147225d6d3a4d06f with token id 274039 found, validating"}
{"reqId":"hfoKAA3UjIsMIH9c6WVl","level":0,"time":"2020-04-16T17:46:36+02:00","remoteAddr":"10.1.10.100","user":"carlos","app":"OC\\User\\Session::validateToken","method":"GET","url":"\/index.php\/apps\/files_textviewer\/","message":"token ffee8cc4ff3314018b5615669a558f46a66a6465a71e094fee40ae73952cd88b3b3cb39b8d91dbee10fd4cda00b876045c7f9d7d39b80c32147225d6d3a4d06f with token id 274039 found, validating"}
```

**Comment by cdamken** [comment]
Probably you can see if something in the changelog changes that do now work with your latest version:
https://doc.owncloud.com/server/10.4/admin_manual/release_notes.html

I'm using PHP 7.3.

If you have questions about my system or you want that me test something, let me know.

**Comment by miqrogroove** [comment]
I've upgraded to 10.4.0 and verified everything is working on my server.  I didn't have any trouble with the Text File Viewer app.

Can you describe what is not working?

**Comment by miqrogroove** [comment]
No issues identified .  If you have a bug, or don't like the navigation icon or some other feature, just follow up here.

**Comment by cdamken** [comment]
Sorry, I was not connected in the last days:
I enable:
<img width="373" alt="Screenshot 2020-04-17 at 17 01 49" src="https://user-images.githubusercontent.com/7264495/80022646-a985a100-84dc-11ea-988c-d483f3372f6d.png">

Then I see:
![Screenshot 2020-04-17 at 16 59 39](https://user-images.githubusercontent.com/7264495/80022681-b5716300-84dc-11ea-84a1-9f8230fd93b1.png)

After that I see when I select:

![Screenshot 2020-04-17 at 17 00 22](https://user-images.githubusercontent.com/7264495/80022739-cb7f2380-84dc-11ea-98d9-b1f4c78c60e1.png)

**Comment by miqrogroove** [comment]
Looks good to me.

**Comment by cdamken** [comment]
Some files can't be opened:

![Screenshot 2020-04-22 at 22 46 50](https://user-images.githubusercontent.com/7264495/80032391-62eb7300-84eb-11ea-9037-a40fc5a44cc5.png)

The black ones can't be selected.

**Comment by miqrogroove** [comment]
Also normal.  There is no practical reason to load a 133 MB text file into your browser.  It would probably crash your browser and could also hit the PHP memory limit on your server.  If you want to manage files that large you are going to need a separate program like Notepad++

**Comment by cdamken** [comment]
ok, thanks
