### ISSUE TITLE
Info about type of files treated as text

### ISSUE THREAD

**Issue by fmalfatto** [miqrogroove/files_textviewer#2]
I would like to view text files mounted as local external storage on owncloud 10, coming from a folder (mounted read only) containing text files of a DNS server, but they are .zone files so the app does not consider them as text. Is it possible to add the .zone filetype to text files list? TY

**Comment by miqrogroove** [comment]
Possible.  This app currently relies on the ownCloud text file types to place the context menu items, but I can see many situations where it might need to be customized.

Alternatively, this app provides the Text browser which will display literally any file as text if it's under a megabyte.  Have you tried this?  You can get there either from the parent folder's context menu, or from the main menu.  This also has the advantage of being faster and easier if you need to get to those files from your phone.

**Comment by fmalfatto** [comment]
Great! The text browser does the trick! TY.
I also tried to add 
        "zone": ["text/plain"],
to the config/mimetypemapping.json but there is a bug and it's ignored.
The problem is solved anyway!

EDIT:
It is solved only for single-dot filenames:
testfile.zone    works
another.testfile.zone      does not work

**Comment by miqrogroove** [comment]
Closing for now.  If it's advantageous in the future, I could change the app to register in all menus instead of the text/plain only.

**Comment by fmalfatto** [comment]
TY. Restarting the owncloud server now it works also for multi-dots filenames.
No need to change your app, regards!
